---
title: "Group by and summarize"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

Load in a dataset that we'll use often

```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>% # date all 01
  select(name, id, everything())
```

## `group_by`

```{r}
weather_df %>%
  group_by(name, month)
```

## Counting things

```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(n_obs = n())

weather_df %>%
  count(month, name = "n_obs") #quick way
```

It is nice that it is df. table does not work
```{r}
weather_df %>%
  pull(month) %>% 
  table
```

```{r}
weather_df %>% 
  janitor::tabyl(month, name)
```

## general summary

count, take mean, look sd

```{r}
weather_df %>%
  #drop_na() %>% 
  group_by(name, month) %>%
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE)
    ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

formatting table outputs

```{r}
qnorm(0.95)
weather_df %>%
  group_by(name) %>%
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),
    ) %>% 
  knitr::kable(digits = 2) # nice table
```

## Grouped `mutate`

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE), # add mean column
    centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) + 
    geom_point() 
```





```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    tmax_rank = min_rank(tmax) # reverse: min_rank(desc(tmax))
    ) %>% # coldest day
  filter(tmax_rank < 2)

```
lagged variables

```{r}
weather_df %>%
  group_by(name) %>%
  mutate(
    lagged_tmax = lag(tmax, n=1), #show the tmax on the day before
    tmax_diff = tmax - lagged_tmax
    ) %>% 
  summarize(
    diff_sd = sd(tmax_diff, na.rm = TRUE)
  )
```

## limitations

what if my "summary" is a linear func

```{r}
weather_df %>%
  group_by(name) %>%
  summarize(
    cor_tmin_tamx = cor(tmin, tmax, use = "complete")
  )

weather_df %>%
  filter(name == "CentralPark_NY") %>% 
  lm(tmax ~ tmin, data = .)

# not work
#weather_df %>%
  #group_by(name) %>%
  #summarize(lm = lm(tmax ~ tmin))
```


