---
title: "ggplot 1"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

Load in a dataset that we'll use often

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

## Scatterplot

tmax vs tmin

```{r}
weather_df %>% 
  ggplot(aes( x = tmin, y = tmax)) + 
  geom_point()


```

you can save ggplots

```{r}
ggp_tmax_tmin =
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

#ggsave()
```

## Let's fancy it up

Add color? lines? other stuff?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = 0.3) + # make it transparent
  geom_smooth(se = FALSE) + # add fitted line
  facet_grid(. ~ name) # seperate graphs
```

Let's make one more scatterplot.

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) + # change dot size
  geom_point(alpha = .3) +
  facet_grid(. ~ name)+
  geom_smooth(se = FALSE)

```

## use data manipulation as part of this

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin * (9/5) + 32 # convert C to F
  ) %>% 
  ggplot(aes(x = date, y = tmax)) +
  geom_point()

```


## stacking geoms

Which geoms do you want?

```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_smooth() 
  
```


```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_bin_2d() 
```

## Univariate plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(. ~ name) # get seperate histogram
```

Let's try some other plots...

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)

```

still with `tmax` and `name`

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

```

some like violin plots?

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()

```

What about rigdes...

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges(alpha = .5, scale = .8) # seperate density plots

```

## Embedding plots

```{r, fig.width = 12}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3)
```















